### ISSUE TITLE
A package for working with XLS and XLSX files

### ISSUE THREAD

**Issue by gryumov** [bhftbootcamp/.github#4]
# Create a package for working with XLS and XLSX files 

You need to create a Julia package that would allow to work with XLS and XLSX files in a convenient and efficient manner. You can either do a pure Julia implementation from scratch or wrap an existing C library.

In case, you want to implement a C wrapper, make sure to change the repo name according to Julia package naming conventions. 

## Tasks

- [ ] Implements read/write
- [ ] Implement convenient getter functions for sheets and tables
- [ ] Implement Excel-like indexing (i.e. A1:B2)
- [ ] Write comprehensive tests, covering edge cases 
- [ ] Benchmark your solution. Be sure to check for any memory leaks. 

## Requirements

Julia provides [Tables.jl](https://tables.juliadata.org/stable/) package that serves as a common interface for any table-like data structures. Adhere to this interface, while developing this package.

Do not do any type inferences! 

### Suggested API

User interface (API) of the package should adhere to the following: 

Creation of base `ExcelBook` object:

```julia
using Excellent

# Passing a byte array from an XLS or XLSX file
xls_book = ExcellentBook(
    read("~/test.xls")
)

xlsx_book = ExcellentBook(
    read("~/test.xlsx")
)
```

Next, implement `excellent_sheetnames` and `excellent_sheet` getters that:

```julia
# Gets a list of all sheet names in a book
excellent_sheetnames(xlsx_book)

# Gets a list of `ExcellentSheet` objects
excellent_sheets(xlsx_book)

# Gets a `ExcellentSheet` by index or name
excellent_sheets(xlsx_book, "Sheet1")
excellent_sheets(xlsx_book, 1)

Get a list of  `ExcellentSheet` by names or ranges
excellent_sheets(xlsx_book, ["Sheet1", "Sheet2"])
excellent_sheets(xlsx_book, 1:2)
```

Now, we are ready to tackle working with the sheets. .

```julia
# Gets a list of all sheet names in a book
excellent_sheetnames(xlsx_book)

# Gets a list of `ExcellentSheet` objects
excellent_sheets(xlsx_book)

# Gets a `ExcellentSheet` by index or name
excellent_sheets(xlsx_book, "Sheet1")
excellent_sheets(xlsx_book, 1)

Get a list of  `ExcellentSheet` by names or ranges
excellent_sheets(xlsx_book, ["Sheet1", "Sheet2"])
excellent_sheets(xlsx_book, 1:2)
```

Now, we can implement convenience functions for working with data. `excellent_select...table` returns a row/col table from the specified range. By default column names should be as in Excel file (i.e. B2:E3 should produce table with B...E column names). If a `header` parameter is specified, then it should be used for column names instead. 

```julia
# Gets the table from the specified range
excellent_select2rowtable(sheet,  "A1:B2"))
excellent_select2coltable(sheet, "A1:B2")

# Or with headers
excellent_select2coltable(sheet, "A1:B2"; headers = ["banana", apple])
```
