### ISSUE TITLE
A package for working with XLS and XLSX files

### ISSUE THREAD

**Issue by gryumov** [bhftbootcamp/.github#5]
# Create a package for working with XLS and XLSX files

You need to create a Julia package that would allow to work with XLSX files in a convenient and efficient manner. You can either do a pure Julia implementation from scratch or wrap an existing C library.

In case, you want to implement a C wrapper, make sure to change the repo name according to Julia package naming conventions. 

## Tasks

- [ ] Implements read/write
- [ ] Implement convenient getter functions for sheets and tables
- [ ] Implement Excel-like indexing (i.e. A1:B2)
- [ ] Write comprehensive tests, covering edge cases 
- [ ] Benchmark your solution. Be sure to check for any memory leaks. 

## Requirements

Julia provides [Tables.jl](https://tables.juliadata.org/stable/) package that serves as a common interface for any table-like data structures. Adhere to this interface, while developing this package.

Do not do any type inferences! 

### Suggested API

User interface (API) of the package should adhere to the following: 

Creation of base `ExcelBook` object:

```julia
using OpenXL

# Passing a byte array from an XLSX file
xlsx_book = parse_xlsx(read("~/test.xlsx"))
```

Next, implement `xl_sheetnames` and `xl_sheet` getters that:

```julia
# Gets a list of all sheet names in a book
xl_sheetnames(xlsx_book)

# Gets a list of `XLSheet` objects
xl_sheets(xlsx_book)

# Gets a `XLSheet` by index or name
xl_sheets(xlsx_book, "Sheet1")
xl_sheets(xlsx_book, 1)

# Get a list of  `XLSheet` by names or ranges
xl_sheets(xlsx_book, ["Sheet1", "Sheet2"])
xl_sheets(xlsx_book, 1:2)
```

Now, we are ready to tackle working with the sheets. .

```julia
# Gets a list of all sheet names in a book
xl_sheetnames(xlsx_book)

# Gets a list of `XLSheet` objects
xl_sheets(xlsx_book)

# Gets a `XLSheet` by index or name
xl_sheets(xlsx_book, "Sheet1")
xl_sheets(xlsx_book, 1)

# Get a list of `XLSheet` by names or ranges
xl_sheets(xlsx_book, ["Sheet1", "Sheet2"])
xl_sheets(xlsx_book, 1:2)
```

Now, we can implement convenience functions for working with data. `xl_...table` returns a row/col table from the specified range. By default column names should be as in Excel file (i.e. B2:E3 should produce table with B...E column names). If a `header` parameter is specified, then it should be used for column names instead. 

```julia
# Gets the table from the specified range
xl_rowtable(xlsx_book, "A1:B2")
xl_columntable(xlsx_book, "A1:B2")

# Or with headers
xl_columntable(xlsx_book, "A1:B2"; headers = ["banana", apple])
```

**Comment by NeroBlackstone** [comment]
I noticed that there is another package [XLSX.jl](https://felipenoris.github.io/XLSX.jl/stable/tutorial/) in the Julia ecosystem that operates XLSX files. 

Do existing XLSX.jl functions meet the requirements? Maybe it's also a good idea to contribute XLSX.jl.

**Comment by gryumov** [comment]
https://github.com/bhftbootcamp/OpenXL.jl

We needed a more flexible interface

**Comment by gryumov** [comment]
> I noticed that there is another package [XLSX.jl](https://felipenoris.github.io/XLSX.jl/stable/tutorial/) in the Julia ecosystem that could manipulate XLSX files.
> 
> Dose XLSX.jl meet the requirements? Maybe it's also a good idea to contribute XLSX.jl.

We needed a more flexible interface

**Comment by gryumov** [comment]
https://github.com/bhftbootcamp/OpenXL.jl
